name: Deploy MERN App to Azure

on:
  push:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: your-backend-app-name
  AZURE_STATIC_WEBAPP_NAME: your-frontend-app-name
  NODE_VERSION: '18.x'

jobs:
  deploy_backend:
    name: Deploy Node.js Backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install
    
    - name: Build backend
      working-directory: ./backend
      run: npm run build --if-present
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./backend

  deploy_frontend:
    name: Deploy React Frontend
    needs: deploy_backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install
    
    - name: Build frontend with production env
      working-directory: ./frontend
      run: |
        npm run build
        echo "REACT_APP_API_BASE_URL=https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net" >> .env.production
    
    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "frontend"
        output_location: "build"